Hide internalName from buyer
MiSArch/frontend pull request #41
Opened 2024-03-11 13:36 UTC by lesser1

Changes:
    - Add hint to text field of Add Product dialog.
    - Remove internal name from product page (ProductView).

[Gropius](https://frontend.gropius.duckdns.org/components/9d12d6ac-e85a-407c-bdff-a8321fb75d3a/issues/6af75f49-6f87-40a1-b905-ebbc8a100725)

### Definition of Done
- [ ] Requirements of the issue are met
- [ ] Code has been reviewed
- [ ] Code is documented

2024-03-17 21:28 UTC, nk-coding approved these changes

2024-03-17 21:39 UTC, nk-coding requested changes
while it does not display it, it still fetches it which still causes an error

2024-03-18 09:25 UTC, lesser1 commented
> while it does not display it, it still fetches it which still causes an error

1296c8b1f6be4c4679ee829baeeca0d4310dc805

2024-03-18 10:40 UTC, nk-coding approved these changes

2024-03-18 11:00 UTC, merged